version: '3.8'
 
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: therootpassword
       MYSQL_DATABASE: redmine

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin:5.0
     ports:
       - "8080:80"
     restart: always
     environment:
        PMA_HOST: db
        PMA_PORT: 3306
 
   redmine:
     depends_on:
       - db
     image: redmine:latest
     volumes:
       - rm_data:/usr/src/redmine/files
     ports:
       - "80:3000"
     restart: always
     environment:
       REDMINE_DB_MYSQL: db
       REDMINE_DB_PASSWORD: therootpassword
       REDMINE_SECRET_KEY_BASE: supersecretkey
volumes:
    db_data: {}
    rm_data: {}
