FROM alpine:latest

WORKDIR /tmp

ADD ./run.sh /bin/

RUN addgroup -S appuser && \
    adduser -S appuser -G appuser

RUN chmod 777 /bin/run.sh

USER appuser

ENTRYPOINT ["/bin/run.sh"]

CMD ["10"]


